### ISSUE TITLE
Github scope on Docs Login page versus Getting Started

### ISSUE THREAD

**Issue by shazron** [smallwins/docs.begin.com#3]
**Expected behavior**
Consistent scope for repos in Github.

**Description of bug**
On begin.com, "Let's get started!" link (bottom) -- the access is for Public repos. But on the docs page, "Login" link (top right) it requires private and public. Which is it? I would only like public repo access for Begin to start. I can't allow Private access to one of the orgs that I am in.

**Steps to reproduce**
Detailed steps to reproduce the behavior:
1. Go to 'https://begin.com'
2. Click on 'Let's get started!' 
3. See scope is Public Repos
4. Click on 'Authorize smallwins'
5. Go to 'https://docs.begin.com/en/getting-started/quickstart/'
6. Click on 'Login' button on the top right
7. See scope is Public and Private

**Desktop**
 - OS: macOS High Sierra 10.13.5
 - Browser: Firefox
 - Version: 61.0.1

**Comment by shazron** [comment]
Perhaps also the bug is, why do I have to login again on the docs.begin.com page when I am already logged in to begin.com

**Comment by kristoferjoseph** [comment]
Thanks Shaz!
Will fix this today.

**Comment by ryanblock** [comment]
Great find, thanks!

Fixed in https://github.com/smallwins/docs.begin.com/commit/589ed441f7efe41c41e4aad6675e26bd8d2d07bb
